name: publish-release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: macos-latest
          TARGET: x86_64-apple-darwin

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl

        - os: windows-latest
          TARGET: x86_64-pc-windows-gnu
          EXTENSION: .exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
      - uses: Swatinem/rust-cache@v1
      - name: Set the tag name
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/*/}
      - name: Set the artifact name
        id: artifact
        run: echo ::set-output name=name::"ARTIFACT=rpg-cli-${{ env.RUNNER_OS }}-${{ steps.tag.outputs.name }}${{ matrix.EXTENSION }}"
      - run: cargo build --release --target ${{ matrix.TARGET }}
      - run: cp target/${{ matrix.TARGET }}/release/rpg-cli${{ matrix.EXTENSION }} ${{ steps.artifact.outputs.name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        # FIXME remove draft
        with:
          draft: true
          files: ${{ steps.artifact.outputs.name }}



# TODO set body from changelog


