name: run-tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: [linux, macos]
    steps:
      # FIXME add cache
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt, clippy
      - run: cargo test --verbose --workspace
      - run: cargo +nightly clippy
      - run: cargo fmt -- --check
      - run: cargo run
      - run: cargo run -- cd -f .
      
